sudo: required

services: 
    - docker

before-install:
    - docker build -t allaeddineattia/react_docker -f Dockerfile.dev .

script: 
    - docker run allaeddineattia/react_docker npm run test -- --coverage --watchAll=false --forceExit
deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-847243026267"
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id:
            secure: "ASIA4KQ46T5N3VU5SS6U"
          secret_access_key:
            secure: "i7+13FHZm20qPdnYylmjrjnYRfi7zc5qPHYu7YGl"