sudo: required

services: 
    - docker

before-install:
    - docker build -t allaeddineattia/react_docker -f Dockerfile.dev .

script: 
    - docker run allaeddineattia/react_docker npm run test -- --coverage